# Language translations
TRANSLATIONS = {
    'en': {
        'welcome': '🔥 Welcome to TrendLens AI!',
        'what_we_do': '🎯 What We Do:',
        'discover': 'Discover VIRAL & TRENDING content from Reddit, YouTube, Twitter, TikTok, Instagram, Facebook and news sources - all in one place!',
        'why_trendlens': '⚡ Why TrendLens?',
        'only_viral': 'We show you ONLY the most viral posts with high views, most comments, and top engagement - NO random content!',
        'categories': '📱 Categories Available:',
        'memes': '😂 Memes - Viral & funny content',
        'gaming': '🎮 Gaming - Latest game news & updates',
        'tech': '💻 Tech - AI, gadgets, programming',
        'sports': '⚽ Sports - Premier League, NBA, more',
        'entertainment': '🎬 Entertainment - Movies, TV shows',
        'news': '📰 News - Breaking news worldwide',
        'jobs': '💼 Jobs - Remote & freelance opportunities',
        'your_status': '👤 Your Status:',
        'quick_start': '💡 Quick Start: Click \'Browse Categories\' below!',
        'browse_categories': '📂 Browse Categories',
        'upgrade_pro': '⭐ Upgrade to Pro',
        'settings': '⚙️ Settings',
        'free_member': '🆓 Free Member',
        'pro_member': '✨ Pro Member',
        'select_category': '📂 Select a category to view trending content:',
        'no_mixing': '🎯 Each category contains only relevant content - no mixing!',
        'back': '« Back',
        'daily_limit': '⚠️ Daily limit reached!',
        'free_limit': 'Free: 10/day | Pro: Unlimited',
        'upgrade': 'Upgrade: /subscribe',
        'banned': '⛔ You are banned from using this bot.',
        'user_not_found': '❌ User not found. Use /start first.',
    },
    'am': {  # Amharic
        'welcome': '🔥 ወደ TrendLens AI እንኳን በደህና መጡ!',
        'what_we_do': '🎯 ምን እናደርጋለን:',
        'discover': 'ከReddit፣ YouTube፣ Twitter፣ TikTok፣ Instagram፣ Facebook እና የዜና ምንጮች ቫይራል እና ትሬንዲንግ ይዘቶችን በአንድ ቦታ ያግኙ!',
        'why_trendlens': '⚡ ለምን TrendLens?',
        'only_viral': 'ከፍተኛ እይታዎች፣ አስተያየቶች እና ተሳትፎ ያላቸውን ቫይራል ፖስቶች ብቻ እናሳያለን - ምንም ዘፈቀደ ይዘት የለም!',
        'categories': '📱 ያሉ ምድቦች:',
        'memes': '😂 ሜምስ - ቫይራል እና አስቂኝ ይዘት',
        'gaming': '🎮 ጌሚንግ - የቅርብ ጊዜ የጨዋታ ዜናዎች',
        'tech': '💻 ቴክኖሎጂ - AI፣ ጋጀቶች፣ ፕሮግራሚንግ',
        'sports': '⚽ ስፖርት - ፕሪሚየር ሊግ፣ NBA፣ ሌሎችም',
        'entertainment': '🎬 መዝናኛ - ፊልሞች፣ የቲቪ ፕሮግራሞች',
        'news': '📰 ዜና - በዓለም ዙሪያ የሚሰበሩ ዜናዎች',
        'jobs': '💼 ስራዎች - የርቀት እና ፍሪላንስ እድሎች',
        'your_status': '👤 የእርስዎ ሁኔታ:',
        'quick_start': '💡 ፈጣን ጅምር: ከታች ያለውን \'ምድቦችን አስስ\' ጠቅ ያድርጉ!',
        'browse_categories': '📂 ምድቦችን አስስ',
        'upgrade_pro': '⭐ ወደ ፕሮ ያሻሽሉ',
        'settings': '⚙️ ቅንብሮች',
        'free_member': '🆓 ነጻ አባል',
        'pro_member': '✨ ፕሮ አባል',
        'select_category': '📂 ትሬንዲንግ ይዘትን ለማየት ምድብ ይምረጡ:',
        'no_mixing': '🎯 እያንዳንዱ ምድብ ተዛማጅ ይዘት ብቻ ይዟል - ምንም መቀላቀል የለም!',
        'back': '« ተመለስ',
        'daily_limit': '⚠️ የዕለት ገደብ ደርሷል!',
        'free_limit': 'ነጻ: 10/ቀን | ፕሮ: ያልተገደበ',
        'upgrade': 'ያሻሽሉ: /subscribe',
        'banned': '⛔ ከዚህ ቦት መጠቀም ታግደዋል።',
        'user_not_found': '❌ ተጠቃሚ አልተገኘም። መጀመሪያ /start ይጠቀሙ።',
    }
}

def get_text(lang, key):
    """Get translated text"""
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, TRANSLATIONS['en'].get(key, key))
